#! /usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';
/**
 * Application release semantic version
 *
 * @see https://semver.org/
 */
define('APP_VERSION', '1.0.0');

$app = new \Symfony\Component\Console\Application( 'Jira Logger', APP_VERSION );

$app->add(new \App\Commands\ConnectCommand);

$app->run();
