#! /usr/bin/env php

<?php
/**
 * Jira Logger CLI Tool
 *
 * @author Mohamed Abdul-Fattah <csmohamed8@gmail.com>
 */

require __DIR__ . '/vendor/autoload.php';
/**
 * Application release semantic version
 *
 * @see https://semver.org/
 */
define('APP_VERSION', '0.5.3');

/**
 * Application name to be displayed on listing commands
 *
 * @var string
 */
$appName = <<< EOL
     _ _             _
    | (_)_ __ __ _  | |    ___   __ _  __ _  ___ _ __
 _  | | | '__/ _` | | |   / _ \ / _` |/ _` |/ _ \ '__|
| |_| | | | | (_| | | |__| (_) | (_| | (_| |  __/ |
 \___/|_|_|  \__,_| |_____\___/ \__, |\__, |\___|_|
                                |___/ |___/
EOL;

$launcher = new \App\Launcher($appName, APP_VERSION);
$launcher->run();
