#! /usr/bin/env php

<?php
/**
 * Jira Logger CLI Tool
 *
 * @author Mohamed Abdul-Fattah <csmohamed8@gmail.com>
 * @since  0.1.0
 */

use App\Commands\StopCommand;
use App\Commands\SyncCommand;
use App\Commands\SetupCommand;
use App\Commands\AbortCommand;
use App\Commands\StartCommand;
use App\Commands\StatusCommand;
use App\Commands\ConnectCommand;
use App\Commands\TimezoneCommand;
use App\Commands\AttributesCommand;
use App\Services\Connect\JiraConnect;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';
/**
 * Application release semantic version
 *
 * @see https://semver.org/
 */
define('APP_VERSION', '0.2.2');

/**
 * Application name to be displayed on listing commands
 *
 * @var string
 */
$appName = <<< EOL
     _ _             _                                
    | (_)_ __ __ _  | |    ___   __ _  __ _  ___ _ __ 
 _  | | | '__/ _` | | |   / _ \ / _` |/ _` |/ _ \ '__|
| |_| | | | | (_| | | |__| (_) | (_| | (_| |  __/ |   
 \___/|_|_|  \__,_| |_____\___/ \__, |\__, |\___|_|   
                                |___/ |___/  
EOL;

$app = new Application($appName, APP_VERSION);

$app->add(new SetupCommand);
$app->add(new ConnectCommand(new JiraConnect));
$app->add(new StartCommand);
$app->add(new StopCommand);
$app->add(new AbortCommand);
$app->add(new StatusCommand);
$app->add(new SyncCommand(new JiraConnect));
$app->add(new TimezoneCommand);
$app->add(new AttributesCommand);

$app->run();
